### ISSUE TITLE
MavenマルチモジュールプロジェクトのJenkinsでのテスト結果一括表示について

### ISSUE THREAD

**Issue by tamamachi** [SahaginOrg/japanese-forum#3]
あるMavenプロジェクトに複数のSahaginを適用したSeleniumプロジェクトがMavenモジュールとして含まれており、
そのMavenプロジェクト全体のテストをJenkinsで実行する場合、すべてのSahaginレポートをJenkinsに表示することはできるのでしょうか。

**Comment by NozomiIto** [comment]
今の機能ではできないですね..

各SeleniumプロジェクトごとにJUnitテスト結果XMLが出力され、その複数の結果XMLを「JUnitテスト結果の集計」の機能などで1つのテスト結果として見ているのでしょうか?

そういった利用をしたいということでしたら、機能追加してみますが。

**Comment by tamamachi** [comment]
Mavenプロジェクトの中にSeleniumテストを行うモジュールがいくつかあり、sahagin.ymlもその数だけあるのですが、
Jenkinsのsahaginプラグインだとsahagin.ymlを一個しか指定できないように見えるので、どうしたものかなあと……

**Comment by NozomiIto** [comment]
そうですね。複数指定はできないですね。

Seleniumテストの実行結果は、Jenkinsの「JUnitテスト結果の集計」を使って、複数のXMLを1箇所に集計して見ているのでしょうか。

**Comment by tamamachi** [comment]
そうですね。Jenkinsの機能で集計して見ています。

**Comment by NozomiIto** [comment]
了解です。次回リリースで対応できるようにしてみます。

**Comment by tamamachi** [comment]
とても助かります！ありがとうごさいます。

**Comment by NozomiIto** [comment]
@tamamachi 

バージョン0.9.2で、マルチプロジェクトのビルドに対応しました。たとえば以下のようなマルチプロジェクトがあった場合、

```
- parent
  - child1
    - sahagin1.yml
    - pom.xml
  - child2
    - sahagin2.yml
    - pom.xml
  - child3
    - sahagin3.yml
    - pom.xml
  - pom.xml
```

sahagin1.ymlとsahagin2.ymlは普通に記述します。

そしてsahagin3.ymlには以下のように記述し、

``` yaml
java:
  testDir: <テストコードのあるディレクトリ>
common:
  reportInputIntermediateDataDirs:
   - sahagin-intermediate-data
   - ../child1/sahagin-intermediate-data
   - ../child2/sahagin-intermediate-data
```

さらにJenkinsのSahaginプラグインのsahagin.ymlのパスには、
`child3/sahagin3.yml`
を指定します。

これで、Jenkinsでレポートを生成する際には、child3以下のSahaginの中間データに加え、child1とchild2以下の中間データも利用するようになるので、3つのプロジェクトを全てまとめたレポートが作成されます。

3つのプロジェクトに同じpackage名かつ同じクラス名のクラスが複数あるとうまくいきません。
